### ISSUE TITLE
Try to avoid testing "implementation details"

### ISSUE THREAD

**Issue by oliverjam** [fac25/testing-Manoela-Karwan#32]
https://github.com/fac25/testing-Manoela-Karwan/blob/da7a96a29c1f1e279001b1ab68863ff8fc4eb3d0/index.test.js#L7-L11

Your tests rely on calling into your JS code directly. This would make it more of a "unit test" than an "integration test", which is fine, but might lead to slightly more brittle or less valuable tests.

For example if for some reason the event listener stopped working
https://github.com/fac25/testing-Manoela-Karwan/blob/da7a96a29c1f1e279001b1ab68863ff8fc4eb3d0/script.js#L46

then your test would keep passing even though your app didn't work anymore.

You usually get more value out of tests that are as close as possible to how a real user would use the app—and a real user cannot call internal functions from your JS. They just interact with the browser, which triggers events that your app responds to.

**Comment by modanova** [comment]
Thank you, Oli. We will instead add a form and a submit button which will be clicked in the test.
